/// <reference path="../pb_data/types.d.ts" />
migrate(
  app => {
    const collection = new Collection({
      createRule: null,
      deleteRule: null,
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          hidden: false,
          id: 'text3208210256',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text',
        },
        {
          cascadeDelete: false,
          collectionId: 'pbc_4080049865',
          hidden: false,
          id: 'relation_patient',
          maxSelect: 1,
          minSelect: 0,
          name: 'patient_id',
          presentable: false,
          required: true,
          system: false,
          type: 'relation',
        },
        {
          hidden: false,
          id: 'json_ssvv_inicial',
          maxSize: 0,
          name: 'ssvv_inicial',
          presentable: false,
          required: false,
          system: false,
          type: 'json',
        },
        {
          hidden: false,
          id: 'json_ssvv_final',
          maxSize: 0,
          name: 'ssvv_final',
          presentable: false,
          required: false,
          system: false,
          type: 'json',
        },
        {
          hidden: false,
          id: 'json_ausculta',
          maxSize: 0,
          name: 'ausculta_pulmonar',
          presentable: false,
          required: false,
          system: false,
          type: 'json',
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text_fisioterapeuta',
          max: 0,
          min: 0,
          name: 'fisioterapeuta',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          hidden: false,
          id: 'date_atendimento',
          max: '',
          min: '',
          name: 'data_atendimento',
          presentable: false,
          required: false,
          system: false,
          type: 'date',
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text_observacao',
          max: 0,
          min: 0,
          name: 'observacao',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          hidden: true,
          id: 'autodate2990389176',
          name: 'created',
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: 'autodate',
        },
        {
          hidden: true,
          id: 'autodate3332085495',
          name: 'updated',
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: 'autodate',
        },
      ],
      id: 'pbc_evolucao_dnm',
      indexes: [],
      listRule: null,
      name: 'evolucao_dnm',
      system: false,
      type: 'base',
      updateRule: null,
      viewRule: null,
    });

    return app.save(collection);
  },
  app => {
    const collection = app.findCollectionByNameOrId('pbc_evolucao_dnm');
    return app.delete(collection);
  }
);
